apiVersion: v1
kind: Namespace
metadata:
  name: forrestereu-1
  namespace: forrestereu-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forrestereu-1
  namespace: forrestereu-1
  labels:
    app: forrestereu-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forrestereu-1
  template:
    metadata:
      labels:
        app: forrestereu-1
    spec:
      containers:
        - name: forrestereu-1
          image: 955116512041.dkr.ecr.us-west-2.amazonaws.com/ld-demo-forrestereu-1-myappimage-vnyaxzkotgoa:latest 
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: forrestereu-1
  name: forrestereu-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: forrestereu-1
  type: LoadBalancer